# Generated by Django 6.0.5 on 2026-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spam_protection', '0002_shield'),
    ]

    operations = [
        migrations.AddField(
            model_name='shield',
            name='blocked_carriers',
            field=models.JSONField(default=list),
        ),
    ]
