# Generated by Django 6.0.5 on 2026-06-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_conversionpixel_conversionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='headers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
