# Generated by Django 6.0.5 on 2026-06-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_transaction_capitalist_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='capitalist_payment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
