# Generated by Django 6.0.5 on 2026-06-08 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kycverification'),
        ('billing', '0004_alter_transaction_capitalist_payment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=20)),
                ('monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('calls_included', models.IntegerField(default=0)),
                ('overage_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('features', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_plans',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='accounts.organization')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.plan')),
            ],
            options={
                'db_table': 'organization_plans',
            },
        ),
    ]
