# Generated by Django 6.0.5 on 2026-06-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='twilio_sid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
