# Generated by Django 6.0.5 on 2026-06-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0002_alter_phonenumber_twilio_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='allocated_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='renews_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='vendor',
            field=models.CharField(choices=[('Twilio', 'Twilio'), ('Telnyx', 'Telnyx'), ('Bandwidth', 'Bandwidth'), ('Vonage', 'Vonage'), ('Other', 'Other')], default='Twilio', max_length=50),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
