# Generated by Django 6.0.5 on 2026-06-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0003_phonenumber_allocated_capacity_phonenumber_renews_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='cap_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='daily_cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
