# Generated by Django 6.0.5 on 2026-06-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0004_phonenumber_cap_enabled_phonenumber_daily_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='concurrency_cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='concurrency_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='dupe_revenue',
            field=models.CharField(default='disabled', max_length=20),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='dupe_revenue_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='monthly_cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='payout_on',
            field=models.CharField(default='connected', max_length=20),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='payout_per_call',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='payout_type',
            field=models.CharField(default='amount', max_length=20),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='traffic_source_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='traffic_source_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='vendor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
