# Generated by Django 6.0.5 on 2026-10-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_numbers', '0007_carrier_phonenumber_assigned_at_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='carrier',
            new_name='phone_numbe_organiz_6ee034_idx',
            old_name='phone_numb_organiz_c7a1d4_idx',
        ),
    ]
