# Generated by Django 6.0.5 on 2026-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_scheduledreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
    ]
