# Generated by Django 6.0.5 on 2026-09-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_callrecord_is_qualified'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecord',
            name='ipqs_line_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
