# Generated by Django 6.0.5 on 2026-10-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_callrecord_block_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecord',
            name='carrier',
            field=models.CharField(blank=True, db_index=True, max_length=60),
        ),
    ]
