# Generated by Django 6.0.5 on 2026-06-22 16:48

import django.db.models.deletion
import referrals.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('vertical', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('churned', 'Churned'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('spend_30d', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lifetime_spend', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='accounts.organization')),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=referrals.models.generate_referral_code, max_length=20, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('lifetime_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('this_month_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_program', to='accounts.organization')),
            ],
            options={
                'db_table': 'referral_programs',
            },
        ),
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='referrals.referral')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='referrals.referralprogram')),
            ],
            options={
                'db_table': 'referral_earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='referral',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='referrals.referralprogram'),
        ),
    ]
