# Generated by Django 6.0.5 on 2026-06-12 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accessrequest_setuptoken'),
        ('buyers', '0006_buyer_quality_score_buyer_quality_score_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tfn', models.CharField(max_length=30)),
                ('forward_type', models.CharField(choices=[('number', 'Phone Number'), ('sip', 'SIP Endpoint')], default='number', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('concurrency_cap', models.IntegerField(default=0)),
                ('hourly_cap', models.IntegerField(default=0)),
                ('daily_cap', models.IntegerField(default=0)),
                ('monthly_cap', models.IntegerField(default=0)),
                ('global_cap', models.IntegerField(default=0)),
                ('live_calls', models.IntegerField(default=0)),
                ('hourly_calls', models.IntegerField(default=0)),
                ('daily_calls', models.IntegerField(default=0)),
                ('monthly_calls', models.IntegerField(default=0)),
                ('global_calls', models.IntegerField(default=0)),
                ('ring_duration_sec', models.IntegerField(default=30)),
                ('timezone', models.CharField(default='America/New_York', max_length=100)),
                ('filter_enabled', models.BooleanField(default=False)),
                ('filter_groups', models.JSONField(default=list)),
                ('business_hours_enabled', models.BooleanField(default=False)),
                ('business_hour_slots', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='buyers.buyer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='accounts.organization')),
            ],
            options={
                'db_table': 'destinations',
                'ordering': ['-created_at'],
            },
        ),
    ]
