# Generated by Django 6.0.5 on 2026-06-15 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0007_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations', to='buyers.buyer'),
        ),
    ]
