# Generated by Django 6.0.5 on 2026-06-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0008_alter_destination_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='buyer',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
