# Generated by Django 6.0.5 on 2026-06-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0009_buyer_contact_email_buyer_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='payout_model',
            field=models.CharField(default='flat', max_length=20),
        ),
    ]
