# Generated by Django 6.0.5 on 2026-06-08 19:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kyc_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('full_legal_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('government_id_url', models.URLField(blank=True, max_length=500)),
                ('company_legal_name', models.CharField(blank=True, max_length=200)),
                ('business_registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('director_name', models.CharField(blank=True, max_length=200)),
                ('business_registration_doc_url', models.URLField(blank=True, max_length=500)),
                ('director_id_url', models.URLField(blank=True, max_length=500)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='accounts.organization')),
            ],
            options={
                'db_table': 'kyc_verification',
            },
        ),
    ]
