# Generated by Django 6.0.5 on 2026-06-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accessrequest_setuptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrequest',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
