# Generated by Django 6.0.5 on 2026-06-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_calllog_sentiment_calllog_sentiment_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='ipqs_block_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='calllog',
            name='ipqs_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calllog',
            name='ipqs_fraud_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='ipqs_is_voip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calllog',
            name='ipqs_line_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
