# Generated by Django 6.0.5 on 2026-06-22 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_payout_model_campaign_vertical_and_more'),
        ('dni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnipool',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dni_pools', to='campaigns.campaign'),
        ),
    ]
