# Generated by Django 6.0.5 on 2026-06-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dni', '0002_alter_dnipool_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnipool',
            name='phone_number_format',
            field=models.CharField(default='E164', max_length=20),
        ),
        migrations.AddField(
            model_name='dnipool',
            name='replacement_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dnipool',
            name='traffic_sources',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dnipool',
            name='traffic_sources_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dnipool',
            name='vendor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dnipool',
            name='vendor_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
