# Generated by Django 6.0.5 on 2026-06-24 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(default='sync', max_length=20)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(default='ok', max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='integrations.organizationintegration')),
            ],
            options={
                'db_table': 'integration_activity',
                'ordering': ['-at'],
            },
        ),
    ]
