# Generated by Django 6.0.5 on 2026-06-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_bid_floor_campaign_rtb_timeout_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='block_invalid_numbers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='block_recent_abuse',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='block_risky',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='block_spammer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='block_voip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ipqs_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_fraud_score',
            field=models.IntegerField(default=85),
        ),
    ]
