# Generated by Django 6.0.5 on 2026-06-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_block_invalid_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='payout_model',
            field=models.CharField(blank=True, choices=[('per_call', 'Per Call'), ('per_qualified', 'Per Qualified'), ('per_minute', 'Per Minute')], default='per_call', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='vertical',
            field=models.CharField(blank=True, choices=[('health', 'Health'), ('auto', 'Auto'), ('home', 'Home'), ('finance', 'Finance'), ('legal', 'Legal'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='campaigncap',
            name='payout_model',
            field=models.CharField(blank=True, choices=[('per_call', 'Per Call'), ('per_qualified', 'Per Qualified'), ('per_minute', 'Per Minute')], default='per_call', max_length=20),
        ),
        migrations.AddField(
            model_name='campaigncap',
            name='vertical',
            field=models.CharField(blank=True, choices=[('health', 'Health'), ('auto', 'Auto'), ('home', 'Home'), ('finance', 'Finance'), ('legal', 'Legal'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
