# Generated by Django 6.0.5 on 2026-06-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_payout_model_campaign_vertical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='advanced_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
